spring.application.name=iniciar

server.port=8081


#useSSL=false  O que é: Define se a conexão com o banco de dados deve ser
# criptografada via SSL (Secure Sockets Layer). O que o valor false faz:
# Desativa a exigência de criptografia SSL na hora de conectar. Por que
# é usado assim: Em ambientes locais de desenvolvimento (localhost),
# geralmente não configuramos certificados SSL no MySQL. Usar false evita erros
# de conexão por falta de certificados de segurança.
# Atenção: Em ambiente de produção, o ideal é usar useSSL=true
# (ou configurar o modo SSL adequado) para proteger os dados em trânsito.

# Conexão com o banco de dados MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/iniciar?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=tifull7.aprendizado
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Hibernate / JPA
#Talvez precise do spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

